//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Break
    {
        public int Id { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public string ShiftDay { get; set; }
        public string BreakId { get; set; }
        public Nullable<System.DateTime> BreakStart { get; set; }
        public Nullable<System.DateTime> BreakEnd { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
