//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string PackageId { get; set; }
        public string OrderId { get; set; }
        public string CompletedBy { get; set; }
        public Nullable<System.DateTime> CompletedDateTime { get; set; }
        public Nullable<System.DateTime> SkidDateTime { get; set; }
        public string ProductGroupCode { get; set; }
        public Nullable<decimal> EquivalentWeightedMean { get; set; }
        public System.DateTime EntDate { get; set; }
    }
}
