//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLog
    {
        public int Id { get; set; }
        public string ShiftId { get; set; }
        public string ShiftDay { get; set; }
        public string LinePrimary { get; set; }
        public string Line { get; set; }
        public string ShiftGoalCount { get; set; }
        public string ShiftActualCount { get; set; }
        public string SecondsPerOrder { get; set; }
        public Nullable<System.DateTime> EntDate { get; set; }
    }
}
