//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgressLog
    {
        public int Id { get; set; }
        public string ProgressId { get; set; }
        public string ShiftId { get; set; }
        public string PrimaryLine { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string CompletedHour { get; set; }
        public string Counts { get; set; }
        public string EquivalentCount { get; set; }
        public string CumulativeCount { get; set; }
        public string Issue { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> EntDate { get; set; }
    }
}
