//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Id { get; set; }
        public string ShiftId { get; set; }
        public string ShiftDay { get; set; }
        public string Line { get; set; }
        public Nullable<int> Members { get; set; }
        public Nullable<int> MemberCapacity { get; set; }
        public Nullable<int> ShiftGoal { get; set; }
        public Nullable<int> ShiftPace { get; set; }
        public Nullable<int> Order_Minutes { get; set; }
        public Nullable<int> Order_Seconds { get; set; }
        public System.DateTime EntDate { get; set; }
    }
}
