'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Break
    Public Property Id As Integer
    Public Property ShiftId As Nullable(Of Integer)
    Public Property ShiftDay As String
    Public Property BreakId As String
    Public Property BreakStart As Nullable(Of Date)
    Public Property BreakEnd As Nullable(Of Date)
    Public Property Description As String
    Public Property Active As Nullable(Of Boolean)

End Class
