'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EventLog
    Public Property Id As Integer
    Public Property EventId As String
    Public Property EventErrorCode As String
    Public Property EventError As String
    Public Property EventDateTime As Nullable(Of Date)

End Class
