'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Order
    Public Property Id As Integer
    Public Property PackageId As String
    Public Property OrderId As String
    Public Property CompletedBy As String
    Public Property CompletedDateTime As Nullable(Of Date)
    Public Property SkidDateTime As Nullable(Of Date)
    Public Property ProductGroupCode As String
    Public Property EquivalentWeightedMean As Nullable(Of Decimal)
    Public Property EntDate As Date

End Class
