'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OrderLog
    Public Property Id As Integer
    Public Property ShiftId As String
    Public Property ShiftDay As String
    Public Property LinePrimary As String
    Public Property Line As String
    Public Property ShiftGoalCount As String
    Public Property ShiftActualCount As String
    Public Property SecondsPerOrder As String
    Public Property EntDate As Nullable(Of Date)

End Class
