'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class OV_DSPEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=OV_DSPEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Orders() As DbSet(Of Order)
    Public Overridable Property Breaks() As DbSet(Of Break)
    Public Overridable Property EventLogs() As DbSet(Of EventLog)
    Public Overridable Property Issues() As DbSet(Of Issue)
    Public Overridable Property OrderLogs() As DbSet(Of OrderLog)
    Public Overridable Property ProgressLogs() As DbSet(Of ProgressLog)
    Public Overridable Property Schedules() As DbSet(Of Schedule)
    Public Overridable Property Shifts() As DbSet(Of Shift)
    Public Overridable Property StatusLogs() As DbSet(Of StatusLog)

End Class
