'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProgressLog
    Public Property Id As Integer
    Public Property ProgressId As String
    Public Property ShiftId As String
    Public Property PrimaryLine As String
    Public Property CompletedDate As Nullable(Of Date)
    Public Property CompletedHour As String
    Public Property Counts As String
    Public Property EquivalentCount As String
    Public Property CumulativeCount As String
    Public Property Issue As String
    Public Property Comment As String
    Public Property EntDate As Nullable(Of Date)

End Class
