'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Schedule
    Public Property Id As Integer
    Public Property ShiftId As String
    Public Property ShiftDay As String
    Public Property Line As String
    Public Property Members As Nullable(Of Integer)
    Public Property MemberCapacity As Nullable(Of Integer)
    Public Property ShiftGoal As Nullable(Of Integer)
    Public Property ShiftPace As Nullable(Of Integer)
    Public Property Order_Minutes As Nullable(Of Integer)
    Public Property Order_Seconds As Nullable(Of Integer)
    Public Property EntDate As Date

End Class
