'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class StatusLog
    Public Property Id As Integer
    Public Property ShiftId As String
    Public Property Lines As String
    Public Property PaceCount As String
    Public Property ActualCount As String
    Public Property EntDate As Nullable(Of Date)

End Class
